export const quartiers = [
  "Abattoir",
  "Adrar",
  "Aghroud 1",
  "Ait melloul",
  "Al Fiddiya",
  "Al Qods",
  "Al Wifaq",
  "Amsernat",
  "Anouar Souss",
  "Anza",
  "Aourir",
  "Autres",
  "Bensergao",
  "Charaf",
  "Cité Suisse",
  "Dakhla",
  "Dcheira",
  "Drarga",
  "El Farah",
  "El Houda",
  "El Massira",
  "Erac - Bouargane",
  "Essalam",
  "Extension Dakhla",
  "Founty",
  "Haut Founty",
  "Hay Al Wafa",
  "Hay Hassani",
  "Hay Mohammadi",
  "Ihchach",
  "Iligh",
  "Imi Ouaddar",
  "Inzegan",
  "La source",
  "Laazib",
  "Les Amicales",
  "Lkhyam 1",
  "Lkhyam 2",
  "Nahda",
  "Najah",
  "Quartier industriel",
  "Riad Salam",
  "Sidi Youssef",
  "Taddart",
  "Taghazout",
  "Taguadirt",
  "Talborjte 1",
  "Tamraght",
  "Tassila",
  "Temsia",
  "Tikiouine",
  "Tilila",
  "Zone touristique",
];
